version: "3"
services:
  laravel:
    build: .
    volumes:
      - .:/var/www/html:delegated
      - ./Docker/php/xdebug.ini:/etc/php/7.2/cli/conf.d/20-xdebug.ini:delegated
      - ./Docker/php/php.ini:/etc/php/7.2/fpm/php.ini:delegated
    environment:
      - VIRTUAL_HOST=laravel.local
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    command: >
      sh -c '
        /etc/init.d/nginx start && /etc/init.d/php7.2-fpm start
        supervisord
      '
    container_name: laravel.local

networks:
  default:
    external:
      name: nginx-proxy
